/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MpTextDescription {
        "titleComponent": string;
    }
}
declare global {
    interface HTMLMpTextDescriptionElement extends Components.MpTextDescription, HTMLStencilElement {
    }
    var HTMLMpTextDescriptionElement: {
        prototype: HTMLMpTextDescriptionElement;
        new (): HTMLMpTextDescriptionElement;
    };
    interface HTMLElementTagNameMap {
        "mp-text-description": HTMLMpTextDescriptionElement;
    }
}
declare namespace LocalJSX {
    interface MpTextDescription {
        "titleComponent"?: string;
    }
    interface IntrinsicElements {
        "mp-text-description": MpTextDescription;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mp-text-description": LocalJSX.MpTextDescription & JSXBase.HTMLAttributes<HTMLMpTextDescriptionElement>;
        }
    }
}
